[versions]
minecraft = "1.20"
parchment = "2023.03.12"
parchmentMinecraft = "1.19.3"
puzzles = "7.0.0"
minPuzzles = "7.0.0"
resources = "15"
data = "15"

# Forge
forge = "1.20-46.0.1"
minForge = "46.0.0"

# Fabric
fabric = "0.14.21"
minFabric = "0.14.21"
fabricApi = "0.83.0+1.20"
minFabricApi = "0.83.0"

# Mods
modmenu = "7.0.1"
bettermodsbutton = "7.0.0"
cardinalcomponents = "5.2.0"
forgeconfigapiport = "7.0.0"
