modLoader = "javafml"
loaderVersion = "[${minForgeFMLVersion},)"
license = "${modLicense}"
issueTrackerURL = "${modIssueUrl}"

[[mods]]
modId = "${modId}"
displayName = "${modName}"
description = "${modDescription}"
version = "${modVersion}"
authors = "${modAuthor}"
logoFile = "mod_banner.png"
logoBlur = false
displayURL = "${modPageUrl}"
updateJSONURL = "${modUpdateUrl}"
displayTest = "${modForgeDisplayTest}"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
type = "required"
versionRange = "[${minForgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "forgeconfigapiport"
mandatory = true
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[modproperties.${ modId }]
catalogueImageIcon = "mod_logo.png"
